# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewGameWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewGameWindowDialog_2(object):
    def setupUi(self, NewGameWindowDialog_2):
        NewGameWindowDialog_2.setObjectName("NewGameWindowDialog_2")
        NewGameWindowDialog_2.setWindowModality(QtCore.Qt.WindowModal)
        NewGameWindowDialog_2.resize(330, 130)
        NewGameWindowDialog_2.setMinimumSize(QtCore.QSize(330, 130))
        NewGameWindowDialog_2.setMaximumSize(QtCore.QSize(330, 130))
        font = QtGui.QFont()
        font.setPointSize(8)
        NewGameWindowDialog_2.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewGameWindowDialog_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(NewGameWindowDialog_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.buttonBox = QtWidgets.QDialogButtonBox(NewGameWindowDialog_2)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_6.addWidget(self.buttonBox, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)

        self.retranslateUi(NewGameWindowDialog_2)
        self.buttonBox.accepted.connect(NewGameWindowDialog_2.accept) # type: ignore
        self.buttonBox.rejected.connect(NewGameWindowDialog_2.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewGameWindowDialog_2)

    def retranslateUi(self, NewGameWindowDialog_2):
        _translate = QtCore.QCoreApplication.translate
        NewGameWindowDialog_2.setWindowTitle(_translate("NewGameWindowDialog_2", "Do you want a new game?"))
        self.label_2.setText(_translate("NewGameWindowDialog_2", "<html><head/><body><p align=\"center\">Are you sure to start a new game?</p><p align=\"center\">Current game will be finished</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewGameWindowDialog_2 = QtWidgets.QDialog()
    ui = Ui_NewGameWindowDialog_2()
    ui.setupUi(NewGameWindowDialog_2)
    NewGameWindowDialog_2.show()
    sys.exit(app.exec_())
